- name: Update apt repo and cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install packages
  apt:
    name:
      - fio
      - ioping
    state: present
    update_cache: true
  become: true

- name: Install fast.com down/up network speed tester
  npm:
    name: "{{ item }}"
    global: yes
    state: present
    unsafe_perm: yes
  with_items:
    - puppeteer
    - fast-cli
  become: true