- name: Download cfssl and cfssljson
  get_url:
    url: "https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/linux/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: '0755'
  with_items:
    - cfssl
    - cfssljson
  become: true

- name: Download kubectl
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl"
    dest: "/usr/local/bin/kubectl"
    mode: '0755'
  become: true
