# Backs up ark saves to /var/cache/rsnapshot/saved-arks/
# The prefix '/var/cache/rsnapshot' comes from the value of 'snapshot_root' in '/etc/rsnapshot.conf'

# Playbook invocation example: ansible-playbook playbook__backup_game_folders.yml -v --extra-vars "host=nocix"

- name: Backup ark saves
  hosts: "{{ host }}"
  remote_user: "{{ remote_default_user }}" # Defined in hosts vars
  roles:
    - backup
  vars_files:
    - secrets/secret_vars.yml
  vars:
    rsnapshot_config_include:
      - "/home/{{ steam_user }}/ark/ShooterGame/Saved/SavedArks/CrystalIsles.ark"
      - "/home/{{ steam_user }}/ark/ShooterGame/Saved/SavedArks/*.arkprofile"
      - "/home/{{ steam_user }}/ark/ShooterGame/Saved/SavedArks/*.arktribe"
    rsnapshot_config_exclude:
      - "/home/{{ steam_user }}/ark/ShooterGame/Saved/SavedArks/*"
    rsnapshot_config_backup:
      - name: ark rsnapshot backup
        backup_folders:
          - [ backup, "/home/{{ steam_user }}/ark/ShooterGame/Saved/SavedArks/", saved-arks/ ]