- name: Configure servers
  hosts: nocix
  remote_user: "{{ remote_default_user }}"
  roles:
    - bootstrap
    - steam
  vars_files:
    - secrets/secret_vars.yml
  vars:
    # - remote_default_user: "user" # DO NOT DEFINE HERE; DEFINE IN HOST,GROUP,TASK, or ROLE vars instead